// <auto-generated />
using System;
using BlazorApp1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250727110906_change props to null")]
    partial class changepropstonull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("BlazorApp1.Entities.Distributor", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonnelCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("Distributors");
                });

            modelBuilder.Entity("BlazorApp1.Entities.Driver", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonnelCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("BlazorApp1.Entities.Personnel", b =>
                {
                    b.Property<int>("PersonnelCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PersonnelCode");

                    b.ToTable("Personnels");
                });

            modelBuilder.Entity("BlazorApp1.Entities.Route", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("BlazorApp1.Entities.Shipment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DistributorName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DistributorPersonnelCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DriverName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DriverPersonnelCode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasVip")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("InvoiceAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InvoiceCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsException")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ReturnInvoiceAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReturnInvoiceCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("SecondServiceInvoiceAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SecondServiceInvoiceCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ShipmentDateGregorian")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipmentDatePersian")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ThirdServiceInvoiceAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ThirdServiceInvoiceCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Weekday")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DistributorName");

                    b.HasIndex("DriverName");

                    b.HasIndex("RouteName");

                    b.HasIndex("WarehouseName");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("BlazorApp1.Entities.ShipmentNumber", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ShipmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("ShipmentNumbers");
                });

            modelBuilder.Entity("BlazorApp1.Entities.Warehouse", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("BlazorApp1.Entities.Shipment", b =>
                {
                    b.HasOne("BlazorApp1.Entities.Distributor", "Distributor")
                        .WithMany("Shipments")
                        .HasForeignKey("DistributorName");

                    b.HasOne("BlazorApp1.Entities.Driver", "Driver")
                        .WithMany("Shipments")
                        .HasForeignKey("DriverName");

                    b.HasOne("BlazorApp1.Entities.Route", "Route")
                        .WithMany("Shipments")
                        .HasForeignKey("RouteName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp1.Entities.Warehouse", "Warehouse")
                        .WithMany("Shipments")
                        .HasForeignKey("WarehouseName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distributor");

                    b.Navigation("Driver");

                    b.Navigation("Route");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("BlazorApp1.Entities.ShipmentNumber", b =>
                {
                    b.HasOne("BlazorApp1.Entities.Shipment", "Shipment")
                        .WithMany("ShipmentNumbers")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("BlazorApp1.Entities.Distributor", b =>
                {
                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("BlazorApp1.Entities.Driver", b =>
                {
                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("BlazorApp1.Entities.Route", b =>
                {
                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("BlazorApp1.Entities.Shipment", b =>
                {
                    b.Navigation("ShipmentNumbers");
                });

            modelBuilder.Entity("BlazorApp1.Entities.Warehouse", b =>
                {
                    b.Navigation("Shipments");
                });
#pragma warning restore 612, 618
        }
    }
}
